# Generated by Django 4.1.1 on 2023-03-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_encard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(max_length=70, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='encard',
            name='description',
            field=models.TextField(max_length=70, verbose_name='Перевод'),
        ),
    ]
