# Generated by Django 4.1.1 on 2023-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_card_description_alter_encard_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='partOfSpeech',
            field=models.CharField(choices=[('Сущ', 'Существительное'), ('Гл', 'Sophomore'), ('Прил', 'Junior'), ('Нар', 'Senior')], default='Сущ', max_length=4),
        ),
    ]
