# Generated by Django 4.1.1 on 2023-03-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_encard_partofspeech_alter_card_partofspeech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='partOfSpeech',
            field=models.CharField(choices=[('(сущ.)', 'Существительное'), ('(гл.)', 'Глагол'), ('(прил.)', 'Прилагательное'), ('(нар.)', 'Наречие'), ('(сч.сл.)', 'Счетное слово'), ('(др.)', 'Другое')], default='(сущ.)', max_length=8),
        ),
        migrations.AlterField(
            model_name='encard',
            name='partOfSpeech',
            field=models.CharField(choices=[('(сущ.)', 'Существительное'), ('(гл.)', 'Глагол'), ('(прил.)', 'Прилагательное'), ('(нар.)', 'Наречие'), ('(др.)', 'Другое')], default='(сущ.)', max_length=7),
        ),
    ]
