# Generated by Django 4.1.1 on 2023-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_card_partofspeech_alter_encard_partofspeech'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='exposition',
            field=models.TextField(default='s', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(max_length=30, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='encard',
            name='description',
            field=models.TextField(max_length=30, verbose_name='Перевод'),
        ),
    ]
