# Generated by Django 4.1.1 on 2023-04-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_card_exposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='exposition',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
