# Generated by Django 4.1.1 on 2023-04-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_card_exposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='encard',
            name='exposition',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
